[tool.poetry]
name = "rag-chatbot"
version = "0.1.0"
description = ""
authors = ["Yash Deshpande <4883988-YashDeshpande1@users.noreply.replit.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flask = "3.1.0"
openai = "1.75.0"
langchain = "0.3.24"
langchain-openai = "0.3.14"
langchain-community = "0.3.22"
faiss-cpu = "1.10.0"
gunicorn = "23.0.0"
pypdf = "5.4.0"
pdfminer-six = "20250416"
python-docx = "1.1.2"
trafilatura = "2.0.0"
python-multipart = "0.0.20"
werkzeug = "3.1.3"
openpyxl = "3.1.5"
email-validator = "2.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
